---
version: 1
policy:
  pullRequests: public
tasks:
  $let:
    $mergeDeep:
      # Defaults
      - should_run: false
        clone_url:
        sha:
      - $switch:
          'tasks_for == "github-pull-request"':
            should_run: {$eval: 'event["action"] in ["opened", "reopened", "synchronize"]'}
            clone_url: ${event.pull_request.head.repo.clone_url}
            sha: ${event.pull_request.head.sha}
          'tasks_for == "github-push"':
            should_run: true
            clone_url: ${event.repository.clone_url}
            sha: ${event.after}
  in:
  - $if: should_run
    then:
      provisionerId: proj-taskcluster
      workerType: ci
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 day'}
      expires: {$fromNow: '1 year 1 second'}  # 1 second so artifacts expire first, despite rounding errors
      payload:
        maxRunTime: 3600
        image: "node:18"
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            git clone ${clone_url} repo &&
            cd repo &&
            git config advice.detachedHead false &&
            git checkout ${sha} &&
            yarn &&
            yarn lint
      metadata:
        name: "taskcluster-net test"
        description: "A landing page at https://taskcluster.net, for those interested in Taskcluster"
        owner: taskcluster-internal@mozilla.com
        source: ${clone_url}
